services:
  punters:
    build: .
    ports:
      - "${HOST_PORT:-80}:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - DATABASE_URL=file:/data/dev.db
    volumes:
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${HOST_PORT:-80}/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    profiles: ["bridged"]

  # Optional host-network variant (Linux only). Use with: docker compose --profile hostnet up -d
  punters-host:
    build: .
    network_mode: host
    environment:
      - NODE_ENV=production
      - PORT=80
      - DATABASE_URL=file:/data/dev.db
    volumes:
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:80/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    profiles: ["hostnet"]
